server:
  port: 9091

spring:
  application:
    name: product_service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_db
    username: postgres
    password: pass@123
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
