spring:
  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5433/restaurant_listing_db
    username: postgres
    password: password
    driver-class-name: org.postgres.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka