spring:
  application:
    name: job-listing
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update  # Options: none, validate, update, create, create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans, mappings, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    enable:
      all: true

